-- 在 Supabase SQL Editor 运行一次。启用 Email 登录；不使用 service_role/secret key。
create table if not exists public.drugs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name text not null check (char_length(trim(name)) between 1 and 120),
  expiry date not null,
  created_at timestamptz not null default now()
);
create index if not exists drugs_user_expiry_idx on public.drugs (user_id, expiry);
alter table public.drugs enable row level security;
revoke all on public.drugs from anon;
grant select, insert, update, delete on public.drugs to authenticated;
grant usage, select on sequence public.drugs_id_seq to authenticated;
drop policy if exists drugs_select_own on public.drugs;
drop policy if exists drugs_insert_own on public.drugs;
drop policy if exists drugs_update_own on public.drugs;
drop policy if exists drugs_delete_own on public.drugs;
create policy drugs_select_own on public.drugs for select to authenticated using ((select auth.uid()) = user_id);
create policy drugs_insert_own on public.drugs for insert to authenticated with check ((select auth.uid()) = user_id);
create policy drugs_update_own on public.drugs for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy drugs_delete_own on public.drugs for delete to authenticated using ((select auth.uid()) = user_id);
